services:
  - type: web
    name: flask-backend
    region: oregon  # or your preferred region
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    runtime: python
    workingDir: backend
    buildFilter:
      paths:
        - backend/**

  - type: static
    name: react-frontend
    runtime: static
    region: oregon
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: build
    workingDir: frontend
    buildFilter:
      paths:
        - frontend/**
