services:
  - type: web
    name: flask-backend
    env: python
    region: oregon  # or your preferred region
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    runtime: python
    workingDir: backend
    buildFilter:
      paths:
        - backend/**

  - type: web
    name: react-frontend
    env: static
    region: oregon
    plan: free
    buildCommand: cd ../frontend && npm install && npm run build
    staticPublishPath: frontend/build
    buildFilter:
      paths:
        - frontend/**
